### ISSUE TITLE
Remote File 'Preview' in the web browser not working

### ISSUE THREAD

**Issue by DEVMaid** [DEVMaid/DEVMaid#16]
At least, for image type resources, on local File 'Preview', it is working as expected:
![remote-file-preview-notworking_1](https://cloud.githubusercontent.com/assets/15973313/11429984/b39b22fc-944d-11e5-9eb6-42e99b565e1d.png)

However, when it comes to remote file 'Preview', it does not show the image
![remote-file-preview-notworking_2](https://cloud.githubusercontent.com/assets/15973313/11429985/b5b59004-944d-11e5-9e52-96163576b2ae.png)

**Comment by DEVMaid** [comment]
![image](https://cloud.githubusercontent.com/assets/15973313/11454111/347620fe-95f0-11e5-87d0-70ba7c3ab94b.png)

Fixed the first part - the file thumbnail but the preview still not working (it is throwing exception). pending to fix later

![image](https://cloud.githubusercontent.com/assets/15973313/11454117/5723492e-95f0-11e5-9300-a27fabd96b53.png)

**Comment by wwken** [comment]
done everything
https://github.com/DEVMaid/DEVMaid/pull/18
