### ISSUE TITLE
The Remote File function: 'Open' and 'Download' in the web browser not working

### ISSUE THREAD

**Issue by DEVMaid** [DEVMaid/DEVMaid#8]
When go to the web browser at http://localhost, then in the Remote file browser for some remote ssh site, try to pick any remote file and right click and choose 'Open'

![open-not-working](https://cloud.githubusercontent.com/assets/15973313/11381954/27ec98fc-92cd-11e5-8422-31eef3066abb.png)

It will generate 500 internal server error:

![open-not-working-2](https://cloud.githubusercontent.com/assets/15973313/11381949/25a1c0fe-92cd-11e5-86dd-718a9efee344.png)

the root cause is the ssh cat has not been implemented.  it needs to be implemented

**Comment by wwken** [comment]
https://github.com/DEVMaid/DEVMaid/pull/14

done
